spring:
  application:
    name: OrderService
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:omsdb;
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.H2Dialect
logging:
  level:
    org:
      hibernate:
        SQL=debug:
server:
  port: 8081
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    preferIpAddress: true

