spring:
  application:
    name: OrderService
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:tcp://localhost:9090/mem:omsdb;
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true
logging:
  level:
    org:
      hibernate:
        SQL=debug:
server:
  port: 8081
